theme: jekyll-theme-minimal
logo: assets/image/ogp.png
title: DIMBULA - Real mobile CI & Computing
description: The real mobile computing under full managed. No-code CI experience for E2E test on real mobile and real mobile computing.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
