theme: jekyll-theme-minimal
title: DIMBULA - The real mobile computing under full managed.
logo: assets/image/icon.png
description: The real mobile computing under full managed. No-code CI experience for E2E test on real mobile and real mobile computing.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
